services:
  sms_db:
    image: postgres:latest
    container_name: sms_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - psql-data:/var/lib/postgresql/data
      # - ./table.sql:/docker-entrypoint-initdb.d/create_tables.sql
  sms_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_sms
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - sms_db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  psql-data:
  pgadmin-data:
  db:
    driver: local